---
- hosts: localhost
  connection: local
  become: true
  vars:
    - pdns_download_url: 'https://downloads.powerdns.com/releases/deb'
    - pdns_server_version: '3.4.8-1'
  tasks:
    - name: Installing ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installing Powerdns Pre-Reqs
      apt:
        name: "{{ item }}"
        state: "present"
        force: "yes"
        install_recommends: no
      with_items:
        - 'jq'
        - 'python-mysqldb'
        - 'mysql-client'

    - name: Installing Powerdns Authoritative
      apt:
        deb: "{{ pdns_download_url }}/pdns-static_{{ pdns_server_version }}_amd64.deb"
        state: "present"
        install_recommends: no
