version: '2'
services:
  db:
    image: mrlesmithjr/mysql:latest
    volumes:
      - "db:/var/lib/mysql"
    ports:
      - "33306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: powerdns
      MYSQL_DATABASE: powerdns
      MYSQL_USER: powerdns
      MYSQL_PASSWORD: powerdns

  pdns_authorative:
    depends_on:
      - db
      - pdns_recursor
    build: ./Authoritative
    image: docker-powerdns-authorative
    links:
      - db
      - pdns_recursor
    ports:
      - "53:53/udp"
      - "8081:8081"
    restart: always
    environment:
      MYSQL_DB_HOSTNAME: db
      MYSQL_DB_USERNAME: powerdns
      MYSQL_DB_PASSWORD: powerdns
      MYSQL_DB_NAME: powerdns
      MYSQL_DB_PORT: 3306

  pdns_recursor:
    build: ./Recursor
    image: docker-powerdns-recursor
    # links:
    #   - db
    # ports:
    #   - "53:53/udp"
    #   - "8081:8081"
    restart: always
    # environment:
    #   MYSQL_DB_HOSTNAME: db
    #   MYSQL_DB_USERNAME: powerdns
    #   MYSQL_DB_PASSWORD: powerdns
    #   MYSQL_DB_NAME: powerdns
    #   MYSQL_DB_PORT: 3306

volumes:
  db:
